# Generated by Django 5.1.4 on 2024-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите ФИО', max_length=100, verbose_name='ФИО')),
                ('team_number', models.PositiveSmallIntegerField(help_text='Укажите номер бригады', verbose_name='Номер бригады')),
                ('salary', models.PositiveIntegerField(help_text='Укажите зарплату', verbose_name='Зарплата')),
                ('specialization', models.CharField(choices=[('rough', 'черновая'), ('fine', 'чистовая'), ('foreman', 'бригадир'), ('taskmaster', 'прораб')], help_text='Укажите специализацию', max_length=20, verbose_name='Специализация')),
            ],
        ),
    ]
