# Generated by Django 5.1.4 on 2024-12-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите ID работника", verbose_name="ID работника"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите ФИО", max_length=100, verbose_name="ФИО"
                    ),
                ),
                (
                    "team_id",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите ID бригады", verbose_name="ID бригады"
                    ),
                ),
                (
                    "salary",
                    models.PositiveIntegerField(
                        help_text="Укажите зарплату", verbose_name="Зарплата"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("rough", "черновая"),
                            ("fine", "чистовая"),
                            ("foreman", "бригадир"),
                            ("taskmaster", "прораб"),
                        ],
                        help_text="Укажите специализацию",
                        max_length=20,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работник",
                "verbose_name_plural": "Работники",
            },
        ),
    ]
